// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHero.Server.Data;

#nullable disable

namespace SuperHero.Server.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231203172712_setData")]
    partial class setData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SuperHero.Server.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Place")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SuperHerois");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Diana",
                            LastName = "Prince",
                            Name = "Mulher Maravilha",
                            Place = "Themyscira"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Natasha",
                            LastName = "Romanoff",
                            Name = "Viúva Negra",
                            Place = "Rússia"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Carol",
                            LastName = "Danvers",
                            Name = "Capitã Marvel",
                            Place = "Boston"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Wanda",
                            LastName = "Maximoff",
                            Name = "Feiticeira Escarlate",
                            Place = "Sokovia"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Ororo",
                            LastName = "Munroe",
                            Name = "Tempestade",
                            Place = "Cairo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
